version: '3'

services:
  demo.test:
    image: local/integration-tests-demo.tests
    build:
      context: ./test/Integration-Tests-Demo.Tests
      dockerfile: Dockerfile
    depends_on:
      - demo.api
      - demo.db
  demo.api:
    image: local/integration-tests-demo.api
    build:
      context: ./src/Integration-Tests-Demo.Api
      dockerfile: Dockerfile
    ports:
      - 5000:80
    depends_on:
      - demo.db
  demo.db:
    image: local/integration-tests-demo.db
    build:
      context: ./src/Integration-Tests-Demo.db
      dockerfile: Dockerfile
    ports:
      - 1401:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Pa33WorD!