version: '3'

services:
  demo.test:
    image: local/integration-tests-demo.tests
    build:
      context: ./test/Integration-Tests-Demo.Tests
      dockerfile: Dockerfile
    depends_on:
      - demo.api
      - demo.db